window.MARATHON_FLASHCARDS = [
{f:"DSAT RW length & structure",b:"2 modules × 27 questions, 32 min each. RW mixes craft/structure, info/ideas, conventions, expression."},
{f:"DSAT Math length",b:"2 modules × 22 questions, 35 min each, 70 total. Calculator allowed on ALL."},
{f:"Comma with FANBOYS",b:"Comma + FANBOYS joins two independent clauses. No FANBOYS → no comma."},
{f:"Semicolon rule",b:"Independent clause ; independent clause. Both sides must stand alone."},
{f:"Colon rule",b:"Independent clause : explanation/list. Left side must be complete."},
{f:"Dash uses",b:"Pair of dashes = parenthetical. Single dash = dramatic colon."},
{f:"Subject-verb flip",b:"Strip prepositional phrases (of, in, with, for, to). Verb agrees with the real subject."},
{f:"Neither/nor rule",b:"Verb agrees with the subject closer to it: 'Neither the students nor the teacher was…'"},
{f:"Pronoun antecedent",b:"'They/it' needs exactly one clear noun. Vague pronoun = wrong."},
{f:"Parallel structure",b:"Lists/comparisons keep same form: to run, to swim, to bike."},
{f:"Transition same direction",b:"Furthermore / moreover / similarly → same-direction continuation only."},
{f:"Transition contrast",b:"However / yet / nevertheless → opposite or unexpected turn."},
{f:"Transition cause",b:"Therefore / thus / consequently → result follows cause."},
{f:"Transition example",b:"For example / for instance → specific instance of prior claim."},
{f:"Vocab-in-context method",b:"Cover choice. Predict exact meaning from sentence. Plug back; check tone + precision."},
{f:"Inference discipline",b:"Must be forced by the text. One step beyond — never two. Eliminate 'could be true'."},
{f:"Evidence match",b:"Proof must support the claim's exact mechanism (numbers, cause, comparison)."},
{f:"Purpose ≠ content",b:"'Function' asks what the part DOES, not what it says. Eliminate true-but-role-less."},
{f:"Hard module target",b:"Get Module 1 ≥ 60% correct. That unlocks Hard Module 2 and 650+ pacing."},
{f:"No-penalty guessing",b:"Score = right − wrong(0). Blank = 0. Always bubble something."},
{f:"Linear slope-intercept",b:"y = mx + b. m = per-unit change; b = y at x=0. Parallel = same m."},
{f:"Perpendicular slopes",b:"m₁·m₂ = −1 (negative reciprocals)."},
{f:"No solution system",b:"Same slope, different intercept → parallel distinct lines."},
{f:"Infinite solutions system",b:"All ratios equal including constants → same line."},
{f:"Percent change formula",b:"(new − old)/old × 100%. Use OLD as base."},
{f:"Markup/discount multipliers",b:"x% increase → ×(1+x/100). x% decrease → ×(1−x/100)."},
{f:"Quadratic vertex",b:"y = a(x−h)² + k → vertex (h,k). x-coord also = −b/(2a)."},
{f:"Discriminant meaning",b:"D=b²−4ac. D>0: 2 real roots; D=0: 1; D<0: none."},
{f:"Exponent rules",b:"a^m·a^n=a^(m+n). (a^m)^n=a^(mn). a^m/a^n=a^(m−n). a^0=1."},
{f:"Radical⇔exponent",b:"ⁿ√x = x^(1/n). √(x²)=|x|."},
{f:"Exponential form",b:"y = a·b^x. a = value at x=0; b = growth/decay factor per unit."},
{f:"Constant diff vs ratio",b:"Linear: constant difference in y. Exponential: constant ratio. Table test."},
{f:"SOH-CAH-TOA",b:"sin=opp/hyp, cos=adj/hyp, tan=opp/adj. Calculator degree mode."},
{f:"Circle equation",b:"(x−h)²+(y−k)² = r². Complete the square to find center and r."},
{f:"Arc & sector",b:"Arc = (θ/360)·2πr. Sector area = (θ/360)·πr². Radians: s=rθ, A=½r²θ."},
{f:"Similar figures scale",b:"Length ×k, area ×k², volume ×k³."},
{f:"Distance/midpoint",b:"d=√((Δx)²+(Δy)²). Midpoint = ((x₁+x₂)/2,(y₁+y₂)/2)."},
{f:"Random sample vs assignment",b:"Random sample → generalize to population. Random assignment → supports causation."},
{f:"Margin of error use",b:"Estimate ± MOE gives plausible interval. Multiply both ends by population for count range."}
];
