window.MARATHON_MATH = [
{id:"M1",name:"Linear equations & systems",domain:"Algebra",freq:"~5/module",highYield:true,secs:75,cue:"One equation → solve for x. Two equations → substitution or elimination. Ask: one solution / no solution / infinite?",pattern:"y = mx + b context or Ax+By=C pair, sometimes with parameter k.",steps:["1 eq: isolate variable. 2 eq: multiply to align coefficients, add/subtract.","For no solution: same slope, different intercept. Infinite: same line (all coefficients proportional).","Desmos: graph both; parallel distinct = none, overlapping = infinite."],wrong:"Matching only x,y coefficients but not constant → calls it 'no solution' when checking infinite.",trap:"T12",desmos:"Graph both lines; or solve({2x+3y=12, x-y=1},{x,y}) intersects."},
{id:"M2",name:"Ratios, rates, percent",domain:"Problem-Solving and Data Analysis",freq:"~4/module",highYield:true,secs:80,cue:"'Percent increase/decrease', 'ratio of', '30% of'. Convert to equation: 0.30× or ×1.30.",pattern:"Word problem with %, part/whole, unit rates.",steps:["Write 'is' = '=', 'of' = '×', 'percent' = '/100'.","Percent change = (new−old)/old."],wrong:"Adding % to a % answer; using base=new instead of old for % change.",trap:"T13",desmos:"None — arithmetic."},
{id:"M3",name:"Quadratics",domain:"Advanced Math",freq:"~4/module",highYield:true,secs:90,cue:"x² appears. Decide: factor, vertex form, quadratic formula, or Desmos.",pattern:"ax²+bx+c=0, vertex max/min, roots/intercepts, discriminant for count of solutions.",steps:["Factor if roots are integers. Else x = (−b ± √(b²−4ac))/2a.","Vertex (h,k) in a(x−h)²+k. Discriminant D: >0 two roots, =0 one, <0 none."],wrong:"Forgetting ± or sign flip in vertex x-coordinate.",trap:"T14",desmos:"Graph y=ax²+bx+c; roots = x-intercepts; vertex = min/max. Double root = touching point."},
{id:"M4",name:"Exponents & roots",domain:"Advanced Math",freq:"~3/module",highYield:true,secs:70,cue:"Variables in exponent or radical. Use laws: a^m·a^n=a^(m+n), (a^m)^n=a^(mn), x^(1/n)=ⁿ√x.",pattern:"Simplify, solve exponential, compare growth.",steps:["Convert radicals to fractional exponents. Match bases before combining.","Solve a^x = b by same-base or exponent rule."],wrong:"Adding exponents when multiplying same base vs multiplying when power-to-power.",trap:"T15",desmos:"Type equivalently to verify: e.g. x^(2/3) vs (x^2)^(1/3) will differ for x<0 sometimes."},
{id:"M5",name:"Linear vs exponential growth",domain:"Problem-Solving and Data Analysis",freq:"~3/module",highYield:true,secs:75,cue:"Table or model. Constant difference → linear. Constant ratio → exponential y=a·b^x.",pattern:"Two scenarios compared, interpret a and b.",steps:["For linear: slope m = Δy/Δx. For exp: b = ratio of consecutive y.","a = y at x=0 (backtrack if table starts later)."],wrong:"Taking first table y as a when x≠0; confusing b with percent instead of rate.",trap:"T16",desmos:"Table in Desmos, then y₁ ~ mx₁+b or y₁ ~ ab^{x₁} for fit."},
{id:"M6",name:"Geometry: lines, angles, triangles",domain:"Geometry and Trigonometry",freq:"~3/module",highYield:true,secs:80,cue:"Figures with parallels, triangles, circles. Same facts: parallels→alt/corr angles, supplementary, triangle sum 180, special triangles 30-60-90/45-45-90.",pattern:"Multi-figure or coordinate geometry with distance formula.",steps:["Mark given angles/parallel lines. Transfer via angle rules.","Distance between points = √((Δx)²+(Δy)²); midpoint average."],wrong:"Assuming right angle without marking; mixing up which triangle is similar.",trap:"T17",desmos:"distance((x1,y1),(x2,y2)); midpoint((x1,y1),(x2,y2)); polygon area via clicking polygon."},
{id:"M7",name:"Circles",domain:"Geometry and Trigonometry",freq:"~2/module",highYield:false,secs:80,cue:"Radius, arc, sector, equation. Equation → complete the square to get center and r.",pattern:"(x−h)²+(y−k)²=r² or arc/sector fraction of circle.",steps:["Arc length = (θ/360)·2πr. Sector area = (θ/360)·πr². Radians: s=rθ, A=½r²θ.","θ in degrees vs radians matters."],wrong:"Using r² as r; degrees in radian formula.",trap:"T18",desmos:"Graph circle equation to read center and r."},
{id:"M8",name:"Functions & function notation",domain:"Advanced Math",freq:"~3/module",highYield:true,secs:70,cue:"f(x), f(x+k), transformation. Plug in, keep order: input inside parentheses first.",pattern:"f(3)=7, find f(a)=…, or composition.",steps:["Substitute carefully with parentheses. For f(g(x)), do inside first.","For transformations: f(x−h) shifts right h."],wrong:"Doing f(x)+k vs f(x+k) same shift.",trap:"T19",desmos:"Type y=f(x) then y=f(x)+2 or y=f(x-3) to see shift."},
{id:"M9",name:"Systems & intersections (nonlinear)",domain:"Advanced Math",freq:"~2/module",highYield:false,secs:85,cue:"Line + parabola, circle + line. Substitute one into other; count distinct real solutions.",pattern:"How many (x,y) satisfy both equations.",steps:["Solve for y in one, plug into other → equation in x. Factor/quad formula.","Repeated root counts once."],wrong:"Counting multiplicity as two points.",trap:"T20",desmos:"Graph both; zoom; count intersection points."},
{id:"M10",name:"Probability & counting",domain:"Problem-Solving and Data Analysis",freq:"~2/module",highYield:true,secs:80,cue:"P(A) = favorable/total. Given condition → replace denominator.",pattern:"Marbles, committees, codes.",steps:["Count total equally likely outcomes. Apply condition (given) to restrict. Favorable count. Reduce.","nCr for groups, nPr for order."],wrong:"Not restricting denominator for 'given'.",trap:"T21",desmos:"Arithmetic only."},
{id:"M11",name:"Statistics & margin of error",domain:"Problem-Solving and Data Analysis",freq:"~2/module",highYield:true,secs:75,cue:"Random sampling → generalize to population. Margin of error → interval. Random assignment → cause.",pattern:"Survey/experiment interpretation.",steps:["Estimate ± MOE = interval. Multiply by population size for count interval.","Voluntary sample → bias; can't generalize. Only randomized experiment supports causation."],wrong:"Claiming cause from observational study.",trap:"T22",desmos:"None."},
{id:"M12",name:"Rational expressions",domain:"Advanced Math",freq:"~2/module",highYield:false,secs:90,cue:"Fractions with variables. Factor, find excluded values FIRST, then simplify/solve. Check solutions against exclusions.",pattern:"Solve (x+1)/(x−2)=…",steps:["Set any original denominator ≠0 → excluded x.","Factor and cancel common factors (but keep exclusions). Solve, then reject excluded."],wrong:"Keeping a root that makes original denominator 0.",trap:"T23",desmos:"Graph both sides; check candidate isn't where both are undefined."},
{id:"M13",name:"Trigonometric ratios (SOH-CAH-TOA)",domain:"Geometry and Trigonometry",freq:"~2/module",highYield:false,secs:80,cue:"Right triangle or unit circle. sin=opp/hyp, cos=adj/hyp, tan=opp/adj.",pattern:"Find missing side/angle.",steps:["Label opposite/adjacent/hypotenuse relative to given angle.","Set up ratio = known/unknown and solve. Calculator in degree mode."],wrong:"Mixing opposite/adjacent.",trap:"T24",desmos:"Check degree mode before any trig."},
{id:"M14",name:"Complex numbers",domain:"Advanced Math",freq:"~1/module",highYield:false,secs:70,cue:"i² = −1. Combine like terms; multiply by conjugate for division.",pattern:"(3+2i)(1−i), (5+i)/(2−i).",steps:["FOIL and replace i² with −1.","For ÷(a+bi), multiply num & den by (a−bi)."],wrong:"Forgetting i²=−1 turns +4i² into +4.",trap:"T25",desmos:"None."}
];
