window.MARATHON_QS_RW = [
{id:"rw-001",section:"RW",type:"RW1",difficulty:"Hard",stem:"The critic's review was notable for its ______: rather than addressing the novel's themes, it focused entirely on the author's biography.\nA) brevity\nB) irrelevance\nC) hostility\nD) precision",options:["brevity","irrelevance","hostility","precision"],answer:"irrelevance",trap:"T01",why:"Focusing on biography instead of themes is off-topic — 'irrelevance' fits. 'Hostility' adds a tone not given.",desmos:"None",secs:60},
{id:"rw-002",section:"RW",type:"RW4",difficulty:"Medium",stem:"According to the passage, Pando is declining primarily because of\nA) invasive plant species\nB) grazing animals eating young trees\nC) insufficient rainfall\nD) competition from other tree colonies",options:["invasive plant species","grazing animals eating young trees","insufficient rainfall","competition from other tree colonies"],answer:"grazing animals eating young trees",trap:"T04",why:"Directly stated: 'in part because of grazing by animals.'",desmos:"None",secs:55},
{id:"rw-003",section:"RW",type:"RW8",difficulty:"Medium",stem:"Which choice correctly completes the sentence?\nThe study was ambitious___its conclusions were limited by the small sample size.\nA) ;\nB) :\nC) ,\nD) —",options:[";",":",",","—"],answer:";",trap:"T08",why:"Both sides are independent clauses; semicolon joins them grammatically.",desmos:"None",secs:45},
{id:"rw-004",section:"RW",type:"RW9",difficulty:"Hard",stem:"Neither the professor nor the students ___ aware of the policy change.\nA) was\nB) were\nC) is\nD) has been",options:["was","were","is","has been"],answer:"were",trap:"T09",why:"With 'neither…nor', verb agrees with NEAREST subject: students (plural) → were.",desmos:"None",secs:50},
{id:"rw-005",section:"RW",type:"RW10",difficulty:"Medium",stem:"Many social media platforms now offer end-to-end encryption. ___, regulators have expressed concern that this may hinder lawful investigations.\nA) Similarly\nB) However\nC) For example\nD) Therefore",options:["Similarly","However","For example","Therefore"],answer:"However",trap:"T10",why:"Second sentence contrasts — concern vs encryption; use however.",desmos:"None",secs:45},
{id:"rw-006",section:"RW",type:"RW5",difficulty:"Hard",stem:"Claim: Urban planners argue that mixed-use development reduces commute times. Which quote best supports the claim?\nA) “Downtown congestion rose 4% last year.”\nB) “A 2023 survey found 62% of residents prefer walkable neighborhoods.”\nC) “Apartments above retail spaces let 41% of workers in City X live within one mile of their jobs.”\nD) “Most cities are investing more in public transit.”",options:["A","B","C","D"],answer:"C",trap:"T05",why:"C gives the mechanism (close to work → shorter commute) with data. B is on-topic but proves preference, not commute reduction.",desmos:"None",secs:65},
{id:"rw-007",section:"RW",type:"RW7",difficulty:"Hard",stem:"Pando's growth is declining. Which can be inferred?\nA) Pando will die within 10 years\nB) Grazing is the only threat to Pando\nC) Fencing may help young trees survive\nD) No deer remain in Utah",options:["A","B","C","D"],answer:"C",trap:"T07",why:"The text supports 'strong fences could prevent deer from eating young trees and help Pando thrive.' Inference stays close — C.",desmos:"None",secs:60},
{id:"rw-008",section:"RW",type:"RW2",difficulty:"Medium",stem:"In a passage about the benefits of urban trees, the sentence 'A 2022 study found that street canopies reduce surface temperatures by up to 12°F' serves to\nA) introduce the central thesis\nB) provide a specific piece of evidence\nC) critique an opposing view\nD) summarize prior research",options:["A","B","C","D"],answer:"B",trap:"T02",why:"Descriptive: gives a concrete supporting fact → evidence.",desmos:"None",secs:60},
{id:"rw-009",section:"RW",type:"RW3",difficulty:"Hard",stem:"Text 1: 'Renewable adoption rose 12% last year.' Text 2: Economists warn grid storage must expand before reliability improves. Both would likely agree that\nA) renewables are unreliable\nB) storage must keep pace with renewables\nC) fossil fuels will remain dominant\nD) no further adoption is needed",options:["A","B","C","D"],answer:"B",trap:"T03",why:"Text 1 says adoption is rising; Text 2 says storage must expand. Shared ground: storage must keep pace.",desmos:"None",secs:65},
{id:"rw-010",section:"RW",type:"RW11",difficulty:"Medium",stem:"Notes: Solar panels reduce household emissions. Installation costs fell 70% since 2010. Goal: emphasize cost reduction. Which choice uses a relevant fact?\nA) Emissions fell in 2022.\nB) Solar panel installation costs fell 70% since 2010.\nC) Homes are more efficient.\nD) Panels last 25 years.",options:["A","B","C","D"],answer:"B",trap:"T11",why:"Goal word is 'cost reduction' → B directly.",desmos:"None",secs:80},
{id:"rw-011",section:"RW",type:"RW6",difficulty:"Medium",stem:"Table: City bike trips: 2019=4.2M, 2020=1.1M, 2021=3.8M, 2022=5.0M. Which claim is best supported?\nA) Trips tripled 2019→2020\nB) Trips fell sharply in 2020 then rebounded by 2022\nC) 2022 had fewer trips than 2019\nD) Trips fell every year",options:["A","B","C","D"],answer:"B",trap:"T06",why:"2020 lowest vs 2019, then recovery to 5.0M by 2022 → B.",desmos:"None",secs:70},
{id:"rw-012",section:"RW",type:"RW12",difficulty:"Hard",stem:"Text: 'Crop yields rose while rainfall stayed constant.' Table shows rainfall unchanged 2018-2020 and yields rising each year. Which inference aligns with BOTH?\nA) Rainfall caused the increase\nB) Another factor, such as fertilizer, may explain yield growth\nC) Yields fell in 2020\nD) Rainfall increased in 2019",options:["A","B","C","D"],answer:"B",trap:"T06",why:"Constant rainfall + rising yields → another factor must contribute → B.",desmos:"None",secs:75}
];
