window.MARATHON_RW = [
{id:"RW1",name:"Words in Context",domain:"Craft and Structure",freq:"~7/module",highYield:true,secs:55,cue:"Blank in one sentence + 4 near-synonyms. Cover choices, predict the word from the sentence's own logic.",pattern:"Single sentence or two-sentence setup with a blank. Choices are same part of speech, subtly different meaning/tone.",steps:["Read the sentence with the blank as an equation — find the clue word that defines it.","Predict your own word before looking.","Test each choice for meaning + tone + direction (positive/negative). Kill related-but-imprecise words."],wrong:"The topic-related word that misses precision; second-best synonym with wrong tone.",trap:"T01",desmos:"None — verbal only."},
{id:"RW2",name:"Text Structure & Purpose",domain:"Craft and Structure",freq:"~4/module",highYield:true,secs:65,cue:"'Which choice best states the function/purpose?' Name each sentence's job first: claim, evidence, example, conclusion.",pattern:"Short passage + 'function of underlined portion' or 'main purpose'.",steps:["Label sentences: setup / claim / support / turn / conclusion.","For underlined part ask: what would break if deleted?","Pick the choice describing ROLE, not just true content."],wrong:"True statement about passage that describes content, not role.",trap:"T02",desmos:"None."},
{id:"RW3",name:"Cross-Text Connections",domain:"Craft and Structure",freq:"~2/module",highYield:true,secs:70,cue:"Two short texts. Question asks how they relate. Track each author's CLAIM separately.",pattern:"Text 1 + Text 2 + 'Based on texts, X would most likely say…'",steps:["One-sentence claim per text.","Find agree/disagree axis.","Test choices against BOTH — must fit Text 2's view of Text 1."],wrong:"Choice true of one text but silent/contradicted by the other.",trap:"T03",desmos:"None."},
{id:"RW4",name:"Central Ideas / Details",domain:"Information and Ideas",freq:"~5/module",highYield:true,secs:60,cue:"'According to the text…' or 'What is the main idea?' Answer must be IN the text, not inferred beyond it.",pattern:"150-word passage + literal comprehension question.",steps:["Find the sentence that directly states it — underline mentally.","Eliminate choices adding a word the passage never said.","For main idea: covers whole passage, not one example."],wrong:"Extreme words (always/never) or detail elevated to main idea.",trap:"T04",desmos:"None."},
{id:"RW5",name:"Command of Evidence (Textual)",domain:"Information and Ideas",freq:"~3/module",highYield:true,secs:65,cue:"Claim + 'Which quotation best supports/illustrates?' Match the CLAIM's exact mechanism.",pattern:"Claim then 4 quotes. Pick supporting evidence.",steps:["Restate claim as testable condition.","Scan quotes for that condition — numbers, causes, comparisons.","Reject quotes that are on-topic but prove a different claim."],wrong:"On-topic quote proving adjacent claim.",trap:"T05",desmos:"None."},
{id:"RW6",name:"Command of Evidence (Quantitative)",domain:"Information and Ideas",freq:"~2/module",highYield:false,secs:75,cue:"Table/graph + claim. Only pick data that BOTH matches numbers AND supports logic.",pattern:"Student notes or table + 'Which data best supports…'",steps:["Read axes/units first.","Translate claim to inequality or comparison.","Check each choice's numbers against table."],wrong:"True data point that supports opposite conclusion.",trap:"T06",desmos:"None."},
{id:"RW7",name:"Inference",domain:"Information and Ideas",freq:"~3/module",highYield:true,secs:65,cue:"'Most logical inference / can reasonably be inferred.' Stay ONE step beyond text, never two.",pattern:"Short passage + what must follow.",steps:["List stated facts.","Ask: what MUST be true, not could be true?","Kill choices needing outside knowledge."],wrong:"Plausible real-world claim not forced by passage.",trap:"T07",desmos:"None."},
{id:"RW8",name:"Boundaries (punctuation)",domain:"Standard English Conventions",freq:"~5/module",highYield:true,secs:50,cue:"Underlined punctuation between clauses. First test: can each side stand alone? Then pick . ; : or ,+FANBOYS vs , / : rules.",pattern:"One sentence, blank or underlined punctuation.",steps:["Split at the mark. Label each side IC (independent clause) or fragment.","IC_IC → period / semicolon / comma+FANBOYS. IC_detail → colon or dash.","Fragment anywhere → comma only if joining correctly."],wrong:"Comma splice (IC,IC with comma alone) or semicolon with fragment.",trap:"T08",desmos:"None."},
{id:"RW9",name:"Form, Structure & Sense (grammar)",domain:"Standard English Conventions",freq:"~5/module",highYield:true,secs:50,cue:"Underlined verb/pronoun/modifier. Find the SUBJECT first — ignore prepositional padding.",pattern:"Verb tense/agreement, pronoun antecedent, modifier placement, parallelism.",steps:["Find subject (strip prepositional phrases).","Match number: singular/plural. Check tense against time clues.","Pronoun must have ONE clear singular/plural antecedent; modifier must touch what it modifies."],wrong:"Verb matching nearest noun instead of subject; ambiguous 'it/they'.",trap:"T09",desmos:"None."},
{id:"RW10",name:"Transitions",domain:"Expression of Ideas",freq:"~4/module",highYield:true,secs:45,cue:"Blank at sentence start + 4 transition words. Map relationship: continue / contrast / cause / example / sequence.",pattern:"Two sentences, blank connecting them.",steps:["Summarize sentence before + after in 4 words each.","Name relationship (same direction? opposite? cause?).","Pick the word with that job — ignore flowery meaning."],wrong:"Same-direction word for opposite sentences.",trap:"T10",desmos:"None."},
{id:"RW11",name:"Rhetorical Synthesis",domain:"Expression of Ideas",freq:"~4/module",highYield:false,secs:80,cue:"Bulleted notes + goal ('emphasize difference', 'present finding'). Only use notes; satisfy EVERY goal word.",pattern:"Notes + 'Which choice most effectively uses relevant information…'",steps:["Underline goal verbs (compare, emphasize, explain).","Pull only the 1–2 bullets containing that info.","Reject choices adding outside info or missing half the goal."],wrong:"Accurate but misses one goal requirement.",trap:"T11",desmos:"None."},
{id:"RW12",name:"Data + Words (paired)",domain:"Information and Ideas",freq:"~1/module",highYield:false,secs:75,cue:"Short text + table. Answer must be consistent with BOTH.",pattern:"Claim about data embedded in prose.",steps:["Read claim, then verify each number.","Watch units and years.","Pick choice true in text AND table."],wrong:"Half-right: matches text, contradicts table.",trap:"T06",desmos:"None."}
];
