window.MARATHON_TRAPS = [
{id:"T01",trap:"Topic-related but imprecise word",check:"Predict your own precise word before looking. Kill 'familiar but off' choices.",example:"Choosing 'hostile' when text only says 'critical'."},
{id:"T02",trap:"True statement that answers a different question",check:"Ask: does this describe what the line DOES (role), not what it SAYS (content)?",example:"Picking an option that restates content but not purpose."},
{id:"T03",trap:"One-text truth presented as cross-text agreement",check:"Choice must fit BOTH texts. If it ignores Text 2, eliminate.",example:"True of Text 1 only."},
{id:"T04",trap:"Extreme absolutes",check:"Always / never / proves — reject unless passage uses same force.",example:"'Pando will definitely die.'"},
{id:"T05",trap:"Adjacent claim evidence",check:"Match the exact mechanism: numbers, cause, comparison — not general topic.",example:"Quote about 'liking walkable areas' ≠ proof commute fell."},
{id:"T06",trap:"Data without direction",check:"Data must support the claim's arrow (up/down/significant/no change).",example:"True stat that supports the opposite trend."},
{id:"T07",trap:"Two-step inference",check:"One step past the text max. Kill 'plausible in the real world'.",example:"Text says 'could help' — choice says 'will help'."},
{id:"T08",trap:"Comma splice / fanboys misuse",check:"If both sides stand alone, need period, semicolon, or comma+FANBOYS. Comma alone = wrong.",example:"'It rained, we stayed.'"},
{id:"T09",trap:"Verb agrees with nearest noun",check:"Cross out prepositional phrases; subject sets the verb.",example:"'The list of items are…' → is."},
{id:"T10",trap:"Flowery transition instead of relationship",check:"Name relationship first (agree/contrast/cause/example), then pick the word with that job.",example:"'For example' between two opposite ideas."},
{id:"T11",trap:"Misses one goal word",check:"Satisfy every verb in the prompt (emphasize difference, present, compare).",example:"Goal 'compare', choice only gives one value."},
{id:"T12",trap:"System solution count error",check:"One line? infinite. Parallel distinct? none. Else one intersection.",example:"Matching only x,y coefficients but forgetting constant → misclassifies."},
{id:"T13",trap:"Wrong percent base",check:"Percent change base is OLD. Markup/discount multipliers: ×(1±r).",example:"(new−old)/new instead of /old."},
{id:"T14",trap:"Sign or vertex slip",check:"x-vertex is −h in (x−h)²; for ax²+bx+c use −b/2a. Plug back.",example:"Saying vertex is (h,k) = (−b/2a's value, value at that x) but dropping the sign."},
{id:"T15",trap:"Exponent rule confusion",check:"Multiply same base → add exponents. Power to power → multiply. Same base divide → subtract.",example:"x²·x³ = x⁶ (wrong)."},
{id:"T16",trap:"First table row mistaken for a",check:"a is y at x=0. If table starts at x>0, backtrack b^x.",example:"Reading y=60 at x=1 as the initial value."},
{id:"T17",trap:"Assumed right angle",check:"Only trust right angles that are marked or provable. Don't eyeball.",example:"Using 3-4-5 without confirming."},
{id:"T18",trap:"Degrees plugged into radian formulas",check:"Convert θ to radians before s=rθ or A=½r²θ. Or use degree fraction.",example:"s = r·72 instead of r·(72π/180)."},
{id:"T19",trap:"Transformation order",check:"f(x−h) shifts right h. Do inside parentheses first for compositions.",example:"f(x+2) as 'shift right 2' — actually left."},
{id:"T20",trap:"Multiplicity counted as points",check:"Repeated root = one (x,y) point. Count distinct ordered pairs.",example:"x² factor giving 'two solutions' when x=0 once."},
{id:"T21",trap:"Ignoring 'given' restriction",check:"'Given B' replaces the denominator with only-B outcomes.",example:"Using total 10C3 instead of 10C3−all-junior."},
{id:"T22",trap:"Observational causation",check:"Random assignment needed for cause claims. Random sample alone generalizes, not proves.",example:"Survey association → 'caused'."},
{id:"T23",trap:"Extraneous root from cleared denominators",check:"Before solving, record excluded x (original denominator ≠0). Reject any solution on that list.",example:"Keeping x=2 after multiplying by (x−2)."},
{id:"T24",trap:"Wrong trig ratio",check:"Label opp/adj relative to the angle. Match to SOH CAH TOA.",example:"Using sin for a side that is adjacent."},
{id:"T25",trap:"Forgetting i² = −1",check:"After expanding, replace every i² with −1. Then combine real & imaginary.",example:"(3+2i)(1−i) = 3−3i+2i−2i² → 3−i+2 = 5−i."},
{id:"T26",trap:"Labeling slope sign error",check:"Negative slope line goes down left-to-right. Check with two points if unsure.",example:"Thinking 'more steep' = 'more positive'."},
{id:"T27",trap:"Confusing area vs length in circles",check:"Arc length is linear; sector area is squared. Use θ/360 × full measure.",example:"Reporting arc length where sector area is asked."},
{id:"T28",trap:"Using mean for skewed data",check:"If data has long tail, median safer. Read which one the question asks.",example:"Picking mean when extreme values pull it."},
{id:"T29",trap:"Units mismatch in word problems",check:"Check units on both sides before trusting a number. Convert minutes/hours before rate.",example:"mph with minutes not converted."},
{id:"T30",trap:"Second-best choice kept too long",check:"After predicting, pick exact match. Don't keep 'pretty close' options alive past 20 seconds.",example:"Choosing a word that is related but weaker."}
];
